// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikqcpnnmhfcsnhocxtst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrcWNwbm5taGZjc25ob2N4dHN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODgyMTIsImV4cCI6MjA2NTU2NDIxMn0.5bYPf7CEbYzyKWX1UsWQ9lTBZGvjX4E2fyTOPA6MT3c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);